// Generated by CoffeeScript 1.6.3
var Drone, RestService,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

RestService = require("./restService");

Drone = (function(_super) {
  __extends(Drone, _super);

  function Drone(baseUrl, accessToken) {
    this.baseUrl = baseUrl;
    this.accessToken = accessToken;
    Drone.__super__.constructor.call(this, "/drone");
  }

  Drone.prototype.addPoints = function(id, trackId, points, callback) {
    if (trackId == null) {
      trackId = null;
    }
    return this.createRequest("" + this.url + "/" + id + "/points", "post").send({
      trackId: trackId,
      points: points || []
    }).end(this.processResult.bind(this, callback));
  };

  Drone.prototype.importPointsFromFiles = function(id, files, format, callback) {
    var file, i, r, _i, _len;
    format = format.toUpperCase();
    if (format !== "CSV" && format !== "KML") {
      return callback(new Error("Format " + (format || '<null>') + " is not supported"));
    }
    r = this.createRequest("" + this.url + "/" + id + "/import" + format, "post");
    i = 1;
    for (_i = 0, _len = files.length; _i < _len; _i++) {
      file = files[_i];
      r = r.attach("file" + i, file);
      i += 1;
    }
    return r.end(this.processResult.bind(this, callback));
  };

  return Drone;

})(RestService);
