// Generated by CoffeeScript 1.6.3
var OAuthHelper, RestService, superagent;

superagent = require("superagent");

RestService = require("./restService");

OAuthHelper = (function() {
  function OAuthHelper(baseUrl, clientId, clientSecret, redirectUrl) {
    this.baseUrl = baseUrl;
    this.clientId = clientId;
    this.clientSecret = clientSecret;
    this.redirectUrl = redirectUrl;
    if (this.baseUrl.length > 0 && this.baseUrl[this.baseUrl.length - 1] === "/") {
      this.baseUrl = this.baseUrl.substr(0, this.baseUrl.length - 1);
    }
  }

  OAuthHelper.prototype.getAccessToken = function(getCode, callback) {
    var url,
      _this = this;
    if (typeof getCode !== "function") {
      return callback(new Error("Parameter getCode must be function"));
    }
    url = "" + this.baseUrl + "/auth/dialog?response_type=code&client_id=" + (encodeURIComponent(this.clientId)) + "&redirect_uri=" + (encodeURIComponent(this.redirectUrl));
    return getCode(url, function(err, code) {
      if (err != null) {
        return callback(err);
      }
      return superagent.post("" + _this.baseUrl + "/auth/token").set("accept", "application/json").send({
        grant_type: "authorization_code",
        code: code,
        redirect_uri: _this.redirectUrl,
        client_id: _this.clientId,
        client_secret: _this.clientSecret
      }).end(function(err, res) {
        var cb;
        cb = function(err, r) {
          if (err != null) {
            return callback(err);
          }
          return callback(null, r.access_token);
        };
        return RestService.processResult(cb, err, res);
      });
    });
  };

  return OAuthHelper;

})();

module.exports = OAuthHelper;
