// Generated by CoffeeScript 1.6.3
var RestService, superagent;

superagent = require("superagent");

superagent.Request.prototype.setAccessToken = function(accessToken) {
  return this.set("Authorization", "Bearer " + accessToken);
};

RestService = (function() {
  function RestService(path) {
    if (this.baseUrl.length > 0 && this.baseUrl[this.baseUrl.length - 1] === "/") {
      this.baseUrl = this.baseUrl.substr(0, this.baseUrl.length - 1);
    }
    this.url = "" + this.baseUrl + "/" + path;
  }

  RestService.prototype.createRequest = function(url, method) {
    if (method == null) {
      method = "get";
    }
    method = method.toLowerCase();
    return superagent[method](url).setAccessToken(this.accessToken).type("json");
  };

  RestService.prototype.processResult = function(callback, err, res) {
    var r;
    if (err != null) {
      return callback(err);
    }
    r = JSON.parse(res.text || "{}");
    if (r.error != null) {
      return callback(new Error(r.error));
    }
    return callback(null, r);
  };

  RestService.prototype.all = function(query, callback) {
    if (query == null) {
      query = null;
    }
    return this.createRequest(this.url).query(query || {}).end(this.processResult.bind(this, callback));
  };

  RestService.prototype.get = function(id, callback) {
    return this.createRequest("" + this.url + "/" + id).end(this.processResult.bind(this, callback));
  };

  RestService.prototype.create = function(item, callback) {
    return this.createRequest(this.url, "post").send(item).end(this.processResult.bind(this, callback));
  };

  RestService.prototype.update = function(item, callback) {
    return this.createRequest("" + this.url + "/" + item.id, "put").send(item).end(this.processResult.bind(this, callback));
  };

  RestService.prototype.remove = function(id, callback) {
    return this.createRequest("" + this.url + "/" + item.id, "del").end(this.processResult.bind(this, callback));
  };

  return RestService;

})();

module.exports = RestService;
