// Generated by CoffeeScript 1.6.3
var Drone, Track, config, createSimpleTrack, createTrack, lib, path, track;

lib = require("../..");

Track = lib.Track;

Drone = lib.Drone;

path = require("path");

config = require("../config");

track = new Track(config.baseUrl, config.accessToken);

createSimpleTrack = function(done) {
  var drone,
    _this = this;
  drone = new Drone(config.baseUrl, config.accessToken);
  return drone.create({
    name: "new Drone"
  }, function(err, d) {
    if (err != null) {
      return done(err);
    }
    return track.create({
      name: "new Track",
      deviceId: d.id
    }, function(err, i) {
      if (err != null) {
        return done(err);
      }
      return done(null, i);
    });
  });
};

createTrack = function() {
  before(function(done) {
    var _this = this;
    return createSimpleTrack(function(err, t) {
      if (err != null) {
        return done(err);
      }
      _this.trackId = t.id;
      _this.droneId = t.deviceId;
      return done();
    });
  });
  return after(function(done) {
    var drone;
    drone = new Drone(config.baseUrl, config.accessToken);
    return drone.remove(this.droneId, done);
  });
};

describe("Track", function() {
  describe("all()", function() {
    return it("should return all track records of current user", function(done) {
      return track.all(function(err, items) {
        if (err != null) {
          return done(err);
        }
        Array.isArray(items).should.be["true"];
        return done();
      });
    });
  });
  describe("create()", function() {
    return it("should create new track", function(done) {
      return track.all(function(err, items) {
        var count;
        if (err != null) {
          return done(err);
        }
        count = items.length;
        return createSimpleTrack(function(err, t) {
          if (err != null) {
            return done(err);
          }
          t.id.should.be.ok;
          t.name.should.equal("new Track");
          return track.all(function(err, items) {
            if (err != null) {
              return done(err);
            }
            items.length.should.equal(count + 1);
            return done();
          });
        });
      });
    });
  });
  describe("get()", function() {
    it("should return track with given id", function(done) {
      return createSimpleTrack(function(err, i) {
        if (err != null) {
          return done(err);
        }
        return track.get(i.id, function(err, item) {
          if (err != null) {
            return done(err);
          }
          item.id.should.equal(i.id);
          item.name.should.equal(i.name);
          return done();
        });
      });
    });
    return it("should fail if track is not exists", function(done) {
      return track.get("id", function(err, item) {
        err.should.be.ok;
        return done();
      });
    });
  });
  describe("update()", function() {
    it("should update track with given id", function(done) {
      return createSimpleTrack(function(err, i) {
        if (err != null) {
          return done(err);
        }
        return track.get(i.id, function(err, item) {
          var name;
          if (err != null) {
            return done(err);
          }
          name = "Name" + (Math.random());
          item.name.should.not.equal(name);
          item.name = name;
          return track.update(item, function(err, it) {
            if (err != null) {
              return done(err);
            }
            it.name.should.equal(name);
            return track.get(i.id, function(err, it) {
              if (err != null) {
                return done(err);
              }
              it.name.should.equal(name);
              return done();
            });
          });
        });
      });
    });
    return it("should fail if track is not exists", function(done) {
      return track.update({
        id: "id",
        name: "Track"
      }, function(err, item) {
        err.should.be.ok;
        return done();
      });
    });
  });
  describe("remove()", function() {
    it("should remove track with given id", function(done) {
      return createSimpleTrack(function(err, i) {
        if (err != null) {
          return done(err);
        }
        return track.all(function(err, items) {
          var count;
          if (err != null) {
            return done(err);
          }
          count = items.length;
          return track.remove(i.id, function(err) {
            if (err != null) {
              return done(err);
            }
            return track.all(function(err, items) {
              if (err != null) {
                return done(err);
              }
              items.length.should.equal(count - 1);
              return done();
            });
          });
        });
      });
    });
    return it("should fail if track is not exists", function(done) {
      return track.remove("id", function(err, item) {
        err.should.be.ok;
        return done();
      });
    });
  });
  describe("addPoints()", function() {
    createTrack();
    it("should add points", function(done) {
      var _this = this;
      return track.addPoints(this.trackId, [
        {
          latitude: 1,
          longitude: 1
        }, {
          latitude: 2,
          longitude: 2
        }
      ], function(err, res) {
        if (err != null) {
          return done(err);
        }
        Array.isArray(res).should.be["true"];
        (res.length >= 2).should.be["true"];
        return done();
      });
    });
    return it("should fail for non-exising track", function(done) {
      var _this = this;
      return track.addPoints("id", [
        {
          latitude: 1,
          longitude: 1
        }, {
          latitude: 2,
          longitude: 2
        }
      ], function(err, res) {
        err.should.be.ok;
        return done();
      });
    });
  });
  describe("importPointsFromFiles()", function() {
    createTrack();
    it("should create new tracks and add points for each csv file", function(done) {
      var files;
      files = [path.join(__dirname, "test1.csv"), path.join(__dirname, "test2.csv")];
      return track.importPointsFromFiles(this.trackId, files, "csv", function(err, res) {
        if (err != null) {
          return done(err);
        }
        return done();
      });
    });
    return it("should create new tracks and add points for each kml file", function(done) {
      var files;
      files = [path.join(__dirname, "test1.kml")];
      return track.importPointsFromFiles(this.trackId, files, "kml", function(err, res) {
        if (err != null) {
          return done(err);
        }
        return done();
      });
    });
  });
  return describe("getPoints()", function() {
    createTrack();
    return it("should return points of the track", function(done) {
      var _this = this;
      return track.addPoints(this.trackId, [
        {
          latitude: 1,
          longitude: 1
        }, {
          latitude: 2,
          longitude: 2
        }
      ], function(err, res) {
        if (err != null) {
          return done(err);
        }
        return track.getPoints(_this.trackId, function(err, pts) {
          if (err != null) {
            return done(err);
          }
          Array.isArray(pts).should.be["true"];
          (pts.length >= 2).should.be["true"];
          return done();
        });
      });
    });
  });
});
